version: 0.2

phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR....
            - aws --version
            - $(aws ecr get-login --region us-east-1 --no-include-email)
            - REPOSITORY_URI=864114915596.dkr.ecr.us-east-1.amazonaws.com/booking
    build:
        commands:
            - echo Build started on `date`..
            - echo Building docker image....
            - ls
            - docker build -t $REPOSITORY_URI:booking -f ./microservices/booking/Dockerfile .
            - docker images           
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the docker image to ECR repository
            - docker push 864114915596.dkr.ecr.us-east-1.amazonaws.com/booking:booking
            - printf '[{"name":"booking","imageUri":"%s"}]' $REPOSITORY_URI:booking > imagedefinitions.json
            - cat imagedefinitions.json
            - aws ecs list-tasks --cluster "booking" --output text | awk '{print $2}' | while read line ; do aws ecs stop-task --task "$line" --cluster "booking" ; done

artifacts:
    files: imagedefinitions.json
    
