version: 0.2

phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR....
            - aws --version
            - $(aws ecr get-login --region us-east-1 --no-include-email)
            - REPOSITORY_URI=864114915596.dkr.ecr.us-east-1.amazonaws.com/profiledb
    build:
        commands:
            - echo Build started on `date`..
            - echo Building docker image....
            - ls
            - docker build -t $REPOSITORY_URI:latest -f ./microservices/login-signup/Dockerfile .
            - docker images
            - docker tag $REPOSITORY_URI:profile profile
            - docker images
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the docker image to ECR repository
            - docker push 864114915596.dkr.ecr.us-east-1.amazonaws.com/profiledb:profile
            - printf '[{"name":"profile","imageUri":"%s"}]' $REPOSITORY_URI:profile > imagedefinitions.json
            - cat imagedefinitions.json
    
